### ISSUE TITLE
SQL file missing

### ISSUE THREAD

**Issue by ghost** [cragcraig/game-of-stones#1]
Project is missing database files, could you upload them ?

**Comment by cragcraig** [comment]
You should be able to navigate to admin/reseter.php which will provide links to create the individual database tables. For security I obviously don't recommend leaving those reset scripts served publicly. That should be all you need to run the game.

You might get in contact with the guy running http://gos.talij.com/ as he's been improving this over the last 7 or so years. I haven't touched this project in almost a decade.
